reports:
  exclude_contracts:
    - SafeMath
dependencies:
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
  - OpenZeppelin/openzeppelin-contracts@3.4.0
compiler:
  solc:
    remappings:
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1"
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.4.0"
# automatically fetch contract sources from Etherscan
autofetch_sources: True
dotenv: .env
# set a custom mnemonic for the development network
networks:
  default: development
  development:
    keyhash: "0x6c3699283bda56ad74f6b855546325b68d482e983852a7a82979cc4807b641f4"
    fee: 100000000000000000
  kovan:
    vrf_coordinator: "0xdD3782915140c8f3b190B5D67eAc6dc5760C46E9"
    link_token: "0xa36085F69e2889c224210F603D836748e7dC0088"
    keyhash: "0x6c3699283bda56ad74f6b855546325b68d482e983852a7a82979cc4807b641f4"
    gas_limit: "100000000000"
    fee: 100000000000000000
    eth_usd_price_feed: "0x9326BFA02ADD2366b30bacB125260Af641031331"
wallets:
  from_key: ${PRIVATE_KEY}
  # You'd have to change the accounts.add to accounts.from_mnemonic to use from_mnemonic
